server:
  port: 9527
  servlet:
    context-path: /shimmer
    # 这将确保所有请求和响应都使用 UTF-8 编码，从而避免编码问题引起的XSS攻击。
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    session:
      cookie:
        # 全局启用HttpOnly等属性，防止csrf等攻击
        http-only: true
        secure: true
        same-site: lax
  # 开启http2支持， http2必须启用ssl
  http2:
    enabled: false
  # 开启https,配置跟证书对应
  ssl:
    enabled: false
    key-store: classpath:https.keystore
    key-store-type: JKS
    # 密码
    key-store-password: 123456
    key-password: 123456
    # 别名
    key-alias: shimmer
  max-http-request-header-size: 8192
  compression:
    enabled: true

logging:
  level:
    _org: INFO
    org:
      hibernate: INFO
      springframework:
        boot:
          autoconfigure:
            logging: INFO

spring:
  application:
    name: shimmer
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      # 指定上载文件允许的最大大小。 默认值为1MB
      max-file-size: 50MB
      # 指定multipart/form-data请求允许的最大大小。 默认值为10MB。
      max-request-size: 50MB
      # 指定将存储上载文件的目录。未指定时，将使用临时目录。
      location: /data/temp
      # 指定文件将写入磁盘的大小阈值。 默认值为0。
      file-size-threshold: 0
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    open-in-view: false
    # 数据库引擎
    database-platform: org.hibernate.dialect.MySQLDialect
    # 数据库
    database: mysql
    # 控制台打印jpa的执行sql
    show-sql: true
    # 是否执行datasource.schema脚本
    generate-ddl: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    # 数据源的类型
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接池hikari配置信息
    hikari:
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 最小空闲连接数量
      minimum-idle: 1
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 60000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 连接池母子
      pool-name: DatebookHikariCP
      # 连接池最大连接数，默认是10
      maximum-pool-size: 5
  flyway:
    enabled: true
    table: app_migration_history
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
  jackson:
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
    # default-property-inclusion: NON_NULL #设置返回json数据null字段不会被序列化,具体属性可看JsonInclude.Include
    # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key请看SerializationFeature源码
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true # 返回的java.util.date转换成timestamp
      FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
    # 枚举类DeserializationFeature中的枚举属性为key，值为boolean设置jackson反序列化特性,具体key请看DeserializationFeature源码
    deserialization:
      # 常用,json中含pojo不存在属性时是否失败报错,默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    # 枚举类MapperFeature中的枚举属性为key，值为boolean设置jackson ObjectMapper特性
    # ObjectMapper在jackson中负责json的读写、json与pojo的互转、json tree的互转,具体特性请看MapperFeature,常规默认即可
    mapper:
      # 使用getter取代setter探测属性，如类中含getName()但不包含name属性与setName()，传输的vo json格式模板中依旧含name属性
      USE_GETTERS_AS_SETTERS: true #默认false
    # 枚举类JsonParser.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonParser特性
    # JsonParser在jackson中负责json内容的读取,具体特性请看JsonParser.Feature，一般无需设置默认即可
    parser:
      ALLOW_SINGLE_QUOTES: true # 是否允许出现单引号,默认false
    # 枚举类JsonGenerator.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonGenerator特性，一般无需设置默认即可
    # JsonGenerator在jackson中负责编写json内容,具体特性请看JsonGenerator.Feature